# Generated by Django 4.0.8 on 2023-02-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
