# Generated by Django 4.0.8 on 2023-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('sports', 'Sports'), ('entertainment', 'Entertainment'), ('pharaonic', 'Pharaonic')], max_length=100, verbose_name='Categories'),
        ),
    ]
