# Generated by Django 4.0.8 on 2023-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='service_type',
            field=models.CharField(default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_type',
            field=models.CharField(default='hotel', max_length=10),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='service_type',
            field=models.CharField(default='restraunt', max_length=10),
        ),
    ]
