# Generated by Django 4.0.8 on 2023-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_restaurant_delete_restraunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cleanlinsess_review',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='review',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='service_review',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='value_review',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(),
        ),
    ]
