# Generated by Django 4.0.8 on 2023-06-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='service_type',
            field=models.CharField(default='historical_place', max_length=17),
        ),
        migrations.AddField(
            model_name='museum',
            name='service_type',
            field=models.CharField(default='museum', max_length=10),
        ),
    ]
