# Generated by Django 4.0.8 on 2023-06-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0003_alter_historicalplace_image_alter_museum_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='it is artfacts')),
                ('present_location', models.CharField(blank=True, max_length=250, null=True)),
                ('inventory', models.CharField(blank=True, max_length=15, null=True)),
                ('dating', models.CharField(blank=True, max_length=250, null=True)),
                ('archeological_site', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(db_index=True, max_length=250)),
                ('technical_details', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/artfacts')),
            ],
        ),
    ]
